version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=farmdb'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=farmer'
    ports:
      - '5432:5432'
